[package]
name = "doggy"
version = "0.1.0"
authors = ["ClSlaid <cailue@bupt.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
itertools = "0.9.0"
regex = "1.4.1"